Test (py-knights-fighting)
mate-academy/py-knights-fighting pull request #374
Opened 2023-08-05 13:58 UTC by baranovr

2023-08-05 14:33 UTC, baranovr commented
Due to these errors, I had to change the original file:

2023-08-06 13:16 UTC, Polyakiv-Andrey requested changes

2023-08-06 13:16 UTC, Polyakiv-Andrey commented on app/main.py
> +    def __init__(self,
After opening the parenthesis, write all the arguments on a new line, including the first one

2023-08-06 13:16 UTC, Polyakiv-Andrey commented on app/main.py
> +
Break your code into multiple modules or files so everything is not in 1 heap

2023-08-06 13:16 UTC, Polyakiv-Andrey commented on app/main.py
> +def battle(knights: Dict) -> Dict:
Add more annotations

2023-08-08 14:32 UTC, baranovr commented
![Снимок экрана 2023-08-08 173238](https://github.com/mate-academy/py-knights-fighting/assets/138402384/d8fc4855-cd0d-4c35-8afb-27aa96d047e6)
![Снимок экрана 2023-08-08 173245](https://github.com/mate-academy/py-knights-fighting/assets/138402384/c4595d4b-f04c-4dfa-ba88-8674f650c086)
![Снимок экрана 2023-08-08 173252](https://github.com/mate-academy/py-knights-fighting/assets/138402384/abd929e3-5312-4576-a2ac-d390748b6525)
Can you advice me: why I have this problem?

2023-08-17 23:01 UTC, closed without merging