After refactoring work the same , but tests failed
mate-academy/py-knights-fighting pull request #423
Opened 2023-09-28 22:31 UTC by OlenaLis123

2023-09-29 09:14 UTC, Bohdan-Salamakha requested changes
fix flake8 errors

2023-09-29 15:05 UTC, OlenaLis123 commented
Fixed

2023-10-04 08:36 UTC, EdAlekseiev requested changes
Flake8 errors are not fixed.

2023-10-05 19:42 UTC, OlenaLis123 commented
https://github.com/mate-academy/py-knights-fighting/pull/433 Вибачте , я дійсно виправила flate 8 app але не помітила , що вона не запушилась , я чомусь так і не зиогла зробити пуш , тому створила нову гілку

2023-10-06 10:45 UTC, ArsenPidhoretskyi requested changes
Please check flake8

2023-10-06 10:45 UTC, ArsenPidhoretskyi commented on app/equipments/weapon.py
> +        return self.power
Add empty line

2023-10-06 10:45 UTC, ArsenPidhoretskyi commented on app/knights.py
> +            potion: Potion = None
potion: Optional[Potion]

2023-10-06 10:45 UTC, ArsenPidhoretskyi commented on app/main.py
> +def battle(KNIGHTS: dict) -> dict:
into function comes knight as dicts, not as object, please read task again

2023-10-06 15:07 UTC, closed without merging