SOL
mate-academy/py-knights-fighting pull request #471
Opened 2023-11-01 21:45 UTC by neagarr

2023-11-02 10:06 UTC, ArsenPidhoretskyi requested changes
Please simplify logic it is so hard

2023-11-02 10:06 UTC, ArsenPidhoretskyi commented on characters/knights.py
> +    list_of_heroes = []
Make it as dict
and prefix list_of_ is redundant

2023-11-02 10:06 UTC, ArsenPidhoretskyi commented on characters/knights.py
> +    list_of_heroes = []
Fix in all places

2023-11-02 10:06 UTC, ArsenPidhoretskyi commented on items/armour.py
> +    list_of_armour = []
Why do you need this?

2023-11-02 10:06 UTC, ArsenPidhoretskyi commented on items/potion.py
> +    list_of_potions = []
Why do you need this?

2023-11-02 10:06 UTC, ArsenPidhoretskyi commented on items/potion.py
> +            self.protection = potion["effect"]["protection"]
Use loop and getattr and setattr

2023-11-02 10:06 UTC, ArsenPidhoretskyi commented on items/weapon.py
> +    list_of_weapons = []
Why do you need this?

2023-11-29 15:00 UTC, neagarr commented
Don't know why so many other files was added to my commit

2023-11-29 15:02 UTC, Grayder0152 requested changes
Pls move envs files to gitignore

2023-11-29 16:42 UTC, vsmutok requested changes
Please remove `vent` form PR

2023-11-29 20:36 UTC, neagarr commented
> Please remove `vent` form PR

what does mean "PR"? )

2023-11-29 22:04 UTC, closed without merging