Solution
mate-academy/py-knights-fighting pull request #553
Opened 2024-01-24 20:10 UTC by kolya2731

2024-01-25 09:28 UTC, vasylhnatiuk requested changes
Create class Knight and save all of knight data in class as atributes, also save functions as methods of this class

2024-01-25 09:28 UTC, vasylhnatiuk commented on app/battle/fight.py
> +def fight(name_1: dict, name_2: dict) -> None:
don't create separate file for one small function

2024-01-25 09:28 UTC, vasylhnatiuk commented on app/battle/check_hp.py
> +def check_hp(name: dict) -> None:
don't create separate file for one small function

2024-01-25 09:28 UTC, vasylhnatiuk commented on app/main.py
> +    mordred = knights_config["mordred"]
don't repeat code, use loops

2024-01-25 09:29 UTC, vasylhnatiuk requested changes
.

2024-02-01 12:56 UTC, pavlejviki requested changes

2024-02-01 14:55 UTC, Polyakiv-Andrey approved these changes
Good job!

2024-12-06 19:56 UTC, closed without merging