checklist created
mate-academy/py-knights-fighting pull request #72
Opened 2022-09-06 14:14 UTC by Y-Havryliv

2022-09-06 14:30 UTC, DmytroSvirsa requested changes
students always forget to use modules let's write something like this - when you work with a big project it's a good idea to separate it into different modules

2022-09-06 14:45 UTC, Y-Havryliv commented
> yeah, sure, I didn't write it, because it's in README already, so I thought to skip it

2022-09-12 07:28 UTC, Abnormaltype requested changes

2022-09-12 07:28 UTC, Abnormaltype commented on checklist.md
> +check_temperature(morning_temprature)
add the output, please

2022-09-12 07:28 UTC, Abnormaltype commented on checklist.md
> +citizens = {"names": ["Dima", "Dania"], "surnames": ["Smith", "Green"]}
please, use indentation

2022-09-12 07:28 UTC, Abnormaltype commented on checklist.md
> +citizens = {"names": ["Dima", "Dania"], "surnames": ["Smith", "Green"]}
please, use indentation

2022-09-12 07:28 UTC, Abnormaltype commented on checklist.md
> +    return f"{x} {y}"
```suggestion
    return f'{x} {y}'
```

2022-09-12 07:28 UTC, Abnormaltype commented on checklist.md
> +def multiply_by_2(number: int) -> Union[int, float]:
```suggestion
def multiply_by_2(number: int) -> int:
```
my bad, I thought, the number would be float

2022-09-12 07:45 UTC, Abnormaltype approved these changes
approved with suggestion

2022-09-12 07:45 UTC, Abnormaltype commented on checklist.md
> +knightsPreparation = "we are preparing"
and add -  `KnightsPreparation` also incorrect

2022-09-12 07:48 UTC, merged

2022-09-12 07:49 UTC, alenatovstukha approved these changes

2022-09-12 07:49 UTC, alenatovstukha commented on checklist.md
> +1. Create functions when needed:
1. Create functions when needed.

2022-09-12 07:49 UTC, alenatovstukha commented on checklist.md
> +2. Use for loops:
2. Use the `for` loops.

2022-09-12 07:49 UTC, alenatovstukha commented on checklist.md
> +3. DRY while creating class instances:
DRY while creating class instances.

DRY - это термин такой или вы просто слово с больших букв написали?

2022-09-12 07:49 UTC, alenatovstukha commented on checklist.md
> +1. Make sure you use the double quotes everywhere.
тут тоже добавьте хороший и плохой примеры

2022-09-12 07:49 UTC, alenatovstukha commented on checklist.md
> +2. Use descriptive and correct variable names:
2. Use descriptive and correct variable names.

2022-09-12 07:49 UTC, alenatovstukha commented on checklist.md
> +3. Use annotation, it is a good practice:
3. Use annotation, it is a good practice.

2022-09-12 07:49 UTC, alenatovstukha commented on checklist.md
> +4. Use `snake_case`:
4. Use the `snake_case`.